version: '3.1'

services:
  web:
    build:
      context: ./configs
      dockerfile: Dockerfile
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
      UID: 1000
    depends_on:
      - db
    volumes:
      - ./site/:/var/www/html/
    ports:
      - 80:80
    stdin_open: true
    tty: true
    networks:
      - shared
  db:
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: databaserest
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    user: 1000:1000
    networks:
    - shared
networks:
  shared:
    external:
      name: shared
